name: Publish canary

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']

jobs:
  publish-canary:
    name: Publish canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      - name: Install deps
        run: bun install
      - name: Publish canary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun release:canary
